package com.set.start3perakende;

import com.set.start3perakende.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author burak
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form AnaMenu
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSales = new javax.swing.JButton();
        BtnReports = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        LblAnaMenu = new javax.swing.JLabel();
        BtnSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSales.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnSales.setText("PERAKENDE SATIŞ");
        BtnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSales.setName(""); // NOI18N
        BtnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalesActionPerformed(evt);
            }
        });

        BtnReports.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnReports.setText("RAPORLAR");
        BtnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportsActionPerformed(evt);
            }
        });

        BtnExit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnExit.setText("ÇIKIŞ");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        LblAnaMenu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LblAnaMenu.setForeground(new java.awt.Color(0, 0, 153));
        LblAnaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblAnaMenu.setText("ANA MENÜ");

        BtnSettings.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnSettings.setText("AYARLAR");
        BtnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblAnaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblAnaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BtnSales)
                .addGap(18, 18, 18)
                .addComponent(BtnReports)
                .addGap(18, 18, 18)
                .addComponent(BtnSettings)
                .addGap(18, 18, 18)
                .addComponent(BtnExit)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(414, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalesActionPerformed
        SalesForm salesForm = new SalesForm();
                salesForm.setVisible(true);
                //salesForm.setBounds(1152 768);

    }//GEN-LAST:event_BtnSalesActionPerformed

    private void BtnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportsActionPerformed

    }//GEN-LAST:event_BtnReportsActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSettingsActionPerformed
        SettingsForm settingsForm = new SettingsForm();
        settingsForm.setVisible(true);
    }//GEN-LAST:event_BtnSettingsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnReports;
    private javax.swing.JButton BtnSales;
    private javax.swing.JButton BtnSettings;
    private javax.swing.JLabel LblAnaMenu;
    // End of variables declaration//GEN-END:variables
}
